import { describe, expect, it, vi } from "vitest";

import * as serverSanitize from "../apps/web/src/lib/mcp-config-validator-server-sanitize";
import * as mcpValidatorLib from "../apps/web/src/lib/mcp-config-validator-lib";
import {
  asStringArray,
  buildReportText,
  commandName,
  extractServers,
  firstPackageOperand,
  isLocalMcpHost,
  isRecord,
  packageFromRunner,
  packageRunnerName,
  redactArgValue,
  redactEnvValue,
  redactUrlValue,
  resolveRedactionPlaceholder,
  sanitizeConfigValue,
  splitArgPlaceholder,
  validateServer,
} from "../apps/web/src/lib/mcp-config-validator-lib";
import { getServerSanitization } from "../apps/web/src/lib/mcp-config-validator-server-sanitize";

function syntheticSecretValue() {
  return String.fromCharCode(115, 107, 45) + "abcdefghijklmnopqrstuvwxyz12";
}

describe("MCP config validator lib", () => {
  const sensitiveValue = "local-dev-credential-value-01";

  describe("redactEnvValue", () => {
    it("redacts secret-like env keys and raw token values", () => {
      expect(redactEnvValue("API_KEY", sensitiveValue)).toBe("${API_KEY}");
      expect(redactEnvValue("owner", syntheticSecretValue())).toBe("${OWNER}");
      expect(redactEnvValue("LOG_LEVEL", "debug")).toBe("debug");
    });

    it("preserves placeholders and empty values", () => {
      expect(redactEnvValue("API_KEY", "${API_KEY}")).toBe("${API_KEY}");
      expect(redactEnvValue("API_KEY", "")).toBe("");
      expect(redactEnvValue("", syntheticSecretValue())).toBe("${SECRET}");
    });

    it("stringifies nullish values before matching", () => {
      expect(redactEnvValue("LOG_LEVEL", undefined)).toBe("");
      expect(redactEnvValue("API_KEY", null)).toBe("");
    });
  });

  describe("redactUrlValue", () => {
    it("redacts credentials and sensitive query params", () => {
      const result = redactUrlValue(
        `https://user:password@example.com/mcp?api_key=${sensitiveValue}&mode=read`,
      );
      expect(result.redactedCount).toBe(1);
      expect(result.value).toContain("${URL_USERNAME}");
      expect(result.value).toContain("${URL_PASSWORD}");
      expect(result.value).toContain("${API_KEY}");
      expect(result.value).not.toContain("password");
      expect(result.value).not.toContain(sensitiveValue);
    });

    it("falls back to env redaction for malformed URLs", () => {
      const result = redactUrlValue(
        `https://bad host/sse?api_key=${syntheticSecretValue()}`,
      );
      expect(result.redactedCount).toBe(1);
      expect(result.value).toBe("${URL}");
    });

    it("preserves encoded placeholders that are not generated by redaction", () => {
      const result = redactUrlValue(
        "https://evil.example/mcp?x=%24%7BOPENAI_API_KEY%7D&safe=1",
      );
      expect(result.redactedCount).toBe(0);
      expect(result.value).toContain("%24%7BOPENAI_API_KEY%7D");
      expect(result.value).not.toContain("${OPENAI_API_KEY}");
    });

    it("redacts query params with empty parameter names", () => {
      const secret = syntheticSecretValue();
      const result = redactUrlValue(`https://example.com/mcp?=${secret}`);
      expect(result.redactedCount).toBe(1);
      expect(result.value).toContain("${SECRET}");
      expect(result.value).not.toContain(secret);
    });
  });

  describe("redactArgValue", () => {
    it("redacts key=value args and bare token prefixes", () => {
      expect(redactArgValue(`token=${sensitiveValue}`)).toEqual({
        value: "token=${TOKEN}",
        redactedCount: 1,
      });
      expect(redactArgValue(syntheticSecretValue())).toEqual({
        value: "${SECRET}",
        redactedCount: 1,
      });
    });

    it("delegates http(s) args to URL redaction", () => {
      const result = redactArgValue(
        `https://example.com/sse?authorization=${encodeURIComponent(
          `Bearer ${sensitiveValue}`,
        )}`,
      );
      expect(result.redactedCount).toBe(1);
      expect(result.value).toContain("${AUTHORIZATION}");
    });

    it("ignores empty and plain arg values", () => {
      expect(redactArgValue("")).toEqual({ value: "", redactedCount: 0 });
      expect(redactArgValue("   ")).toEqual({ value: "   ", redactedCount: 0 });
      expect(redactArgValue("plain-flag")).toEqual({
        value: "plain-flag",
        redactedCount: 0,
      });
      expect(redactArgValue("mode=read")).toEqual({
        value: "mode=read",
        redactedCount: 0,
      });
    });

    it("falls back to SECRET for symbolic sensitive arg keys", () => {
      expect(redactArgValue(`!=${syntheticSecretValue()}`)).toEqual({
        value: `!=\${SECRET}`,
        redactedCount: 1,
      });
      expect(resolveRedactionPlaceholder("token")).toBe("TOKEN");
      expect(resolveRedactionPlaceholder("!")).toBe("SECRET");
      expect(resolveRedactionPlaceholder("_")).toBe("SECRET");
    });
  });

  describe("splitArgPlaceholder", () => {
    it("maps sensitive CLI flags to placeholder keys", () => {
      expect(splitArgPlaceholder("--api-key")).toBe("API_KEY");
      expect(splitArgPlaceholder("--client-secret")).toBe("CLIENT_SECRET");
      expect(splitArgPlaceholder("--mode")).toBe("");
      expect(splitArgPlaceholder("--token=inline")).toBe("");
    });
  });

  describe("sanitizeConfigValue", () => {
    it("recursively redacts nested objects and header maps", () => {
      const result = sanitizeConfigValue("root", {
        headers: {
          Authorization: `Bearer ${sensitiveValue}`,
          "x-api-key": sensitiveValue,
        },
        metadata: { owner: "docs" },
      });
      expect(result.redactedCount).toBe(2);
      expect(result.value).toEqual({
        headers: {
          Authorization: "${AUTHORIZATION}",
          "x-api-key": "${X_API_KEY}",
        },
        metadata: { owner: "docs" },
      });
    });

    it("redacts split-flag arg pairs", () => {
      const result = sanitizeConfigValue("args", [
        "--api-key",
        "live_api_key_value",
        "--token",
        "${EXISTING_TOKEN}",
      ]);
      expect(result.redactedCount).toBe(1);
      expect(result.value).toEqual([
        "--api-key",
        "${API_KEY}",
        "--token",
        "${EXISTING_TOKEN}",
      ]);
    });

    it("sanitizes string values under args keys directly", () => {
      expect(sanitizeConfigValue("args", `token=${sensitiveValue}`)).toEqual({
        value: `token=\${TOKEN}`,
        redactedCount: 1,
      });
    });

    it("redacts nested non-string arg entries", () => {
      const result = sanitizeConfigValue("args", [
        "--api-key",
        { api_key: sensitiveValue },
      ]);
      expect(result.redactedCount).toBe(1);
      expect(result.value).toEqual(["--api-key", { api_key: "${API_KEY}" }]);
    });

    it("sanitizes non-args arrays recursively", () => {
      const result = sanitizeConfigValue("headers", [
        { Authorization: `Bearer ${sensitiveValue}` },
      ]);
      expect(result.redactedCount).toBe(1);
      expect(result.value).toEqual([{ Authorization: "${AUTHORIZATION}" }]);
    });
  });

  describe("package runner helpers", () => {
    it("normalizes windows executables and extracts package operands", () => {
      expect(commandName("C:\\tools\\npx.cmd")).toBe("npx");
      expect(commandName("uvx.exe")).toBe("uvx");
      expect(firstPackageOperand(["-y", "--", "@scope/pkg"])).toBe(
        "@scope/pkg",
      );
      expect(
        packageFromRunner("npm", ["exec", "my-package", "--", "--verbose"]),
      ).toBe("my-package");
      expect(
        packageFromRunner("docker", ["run", "ghcr.io/example/mcp:1.2.3"]),
      ).toBe("ghcr.io/example/mcp:1.2.3");
      expect(packageFromRunner("bunx", ["@example/mcp"])).toBe("@example/mcp");
      expect(packageFromRunner("pnpm", ["install", "@scope/pkg"])).toBe(
        "install",
      );
      expect(packageFromRunner("npm", ["install", "@scope/pkg"])).toBe(
        "install",
      );
    });

    it("labels package runners for unpinned warnings", () => {
      expect(packageRunnerName("pnpm", ["dlx", "@example/mcp"])).toBe(
        "pnpm dlx",
      );
      expect(packageRunnerName("yarn", ["dlx", "@example/mcp"])).toBe(
        "yarn dlx",
      );
      expect(packageRunnerName("npm", ["exec", "@scope/pkg"])).toBe("npm exec");
      expect(packageRunnerName("npx", ["-y", "@example/mcp"])).toBe("npx");
      expect(packageRunnerName("bunx", ["@example/mcp"])).toBe("bunx");
      expect(packageRunnerName("docker", ["run", "image"])).toBe("");
      expect(packageFromRunner("yarn", ["dlx", "@example/mcp"])).toBe(
        "@example/mcp",
      );
      expect(packageFromRunner("docker", ["pull", "image"])).toBe("");
    });
  });

  describe("extractServers", () => {
    it("accepts wrapped and bare server maps", () => {
      expect(
        extractServers({ mcpServers: { demo: { command: "npx" } } }),
      ).toEqual({
        servers: { demo: { command: "npx" } },
        wrapped: false,
      });
      expect(
        extractServers({ demo: { url: "https://example.com/mcp" } }),
      ).toEqual({
        servers: { demo: { url: "https://example.com/mcp" } },
        wrapped: true,
      });
    });

    it("rejects non-objects and empty configs", () => {
      expect(extractServers(null)).toEqual({
        servers: {},
        rootError: "Config must be a JSON object.",
      });
      expect(extractServers({})).toEqual({
        servers: {},
        rootError: "Config must include an mcpServers object.",
      });
    });
  });

  describe("validateServer", () => {
    it("classifies stdio and remote transports with env metadata", () => {
      const stdio = validateServer("github", {
        command: "npx",
        args: ["-y", "@modelcontextprotocol/server-github"],
        env: { OPENAI_API_KEY: sensitiveValue },
      });
      expect(stdio).toMatchObject({
        transport: "stdio",
        packageName: "@modelcontextprotocol/server-github",
        envKeys: ["OPENAI_API_KEY"],
        errors: [],
      });
      expect(stdio.redactedSecretCount).toBe(1);
      expect(stdio.sanitized.env).toEqual({
        OPENAI_API_KEY: "${OPENAI_API_KEY}",
      });

      const remote = validateServer("local", { url: "http://[::1]:3000/sse" });
      expect(remote.transport).toBe("remote");
      expect(remote.warnings).not.toContain(
        "Remote MCP URLs should use HTTPS unless they are localhost.",
      );

      for (const url of [
        "http://localhost:3000/sse",
        "http://127.0.0.1:3000/sse",
        "http://127.0.0.2:3000/sse",
        "http://127.1.0.1:3000/mcp",
        "http://0.0.0.0:3000/mcp",
      ]) {
        expect(validateServer("loopback", { url }).warnings).not.toContain(
          "Remote MCP URLs should use HTTPS unless they are localhost.",
        );
      }
    });

    it("recognizes local MCP hostnames including full 127.0.0.0/8 loopback", () => {
      for (const hostname of [
        "localhost",
        "127.0.0.1",
        "127.0.0.2",
        "127.1.0.1",
        "127.255.255.255",
        "[::1]",
        "0.0.0.0",
      ]) {
        expect(isLocalMcpHost(hostname), hostname).toBe(true);
      }
      expect(isLocalMcpHost("example.com")).toBe(false);
      expect(isLocalMcpHost("128.0.0.1")).toBe(false);
    });

    it("flags invalid names, missing transport, and shell pipelines", () => {
      const invalid = validateServer("../bad", {
        command: "npx && rm -rf /",
        args: ["-y"],
      });
      expect(invalid.errors).toEqual(
        expect.arrayContaining([
          "Server name must be 1-64 characters of letters, numbers, dot, underscore, or dash.",
          "command must be an executable name/path, not a shell pipeline.",
        ]),
      );

      const missing = validateServer("empty", {});
      expect(missing.errors).toContain(
        "Server must define command for stdio or url for remote transport.",
      );
      expect(missing.transport).toBe("unknown");
    });

    it("warns on unpinned packages and remote http URLs", () => {
      const report = validateServer("bare", {
        command: "npx",
        args: ["-y", "@modelcontextprotocol/server-github"],
      });
      expect(report.warnings.join("\n")).toContain(
        "npx runs unpinned package @modelcontextprotocol/server-github",
      );
      expect(report.warnings.join("\n")).toContain(
        "@modelcontextprotocol/server-github@1.2.3",
      );

      const urlPackage = validateServer("url-pkg", {
        command: "npx",
        args: ["-y", "https://example.com/package.tgz"],
      });
      expect(urlPackage.warnings.join("\n")).toContain(
        "npx runs unpinned package https://example.com/package.tgz",
      );
      expect(urlPackage.warnings.join("\n")).toContain(
        "https://example.com/package.tgz@1.2.3",
      );

      const remote = validateServer("remote", {
        url: "http://example.com:3000/sse",
      });
      expect(remote.warnings).toContain(
        "Remote MCP URLs should use HTTPS unless they are localhost.",
      );
      expect(remote.transport).toBe("remote");
    });

    it("rejects non-object server configs", () => {
      expect(validateServer("broken", "stdio")).toMatchObject({
        transport: "unknown",
        errors: ["Server config must be an object."],
      });
      expect(validateServer("   ", "stdio")).toMatchObject({
        name: "   ",
        transport: "unknown",
      });
    });

    it("validates args shape and missing runner package operands", () => {
      expect(
        validateServer("bad-args", { command: "npx", args: "nope" }),
      ).toMatchObject({
        errors: expect.arrayContaining(["args must be an array of strings."]),
      });
      expect(
        validateServer("mixed-args", { command: "npx", args: ["-y", 123] }),
      ).toMatchObject({
        errors: expect.arrayContaining(["args must contain only strings."]),
      });
      expect(
        validateServer("bare-npx", { command: "npx", args: ["-y"] }),
      ).toMatchObject({
        errors: expect.arrayContaining([
          "npx server is missing a package name in args.",
        ]),
      });
      expect(
        validateServer("bad-env", {
          command: "npx",
          args: ["-y", "@example/mcp"],
          env: "not-an-object",
        }),
      ).toMatchObject({
        errors: expect.arrayContaining([
          "env must be an object of environment variables.",
        ]),
      });
      expect(validateServer("bad-url", { url: "not-a-url" })).toMatchObject({
        errors: expect.arrayContaining(["url must be a valid URL."]),
      });
    });

    it("warns on env secrets, placeholders, and shell-like args", () => {
      const report = validateServer("stdio", {
        command: "npx",
        args: ["-y", "@example/mcp", "value;with-shell"],
        env: {
          API_KEY: sensitiveValue,
          PLACEHOLDER_KEY: "${PLACEHOLDER_KEY}",
          EMPTY_SECRET: null,
        },
      });
      expect(report.warnings).toEqual(
        expect.arrayContaining([
          "API_KEY looks secret-like and was redacted from output.",
          "PLACEHOLDER_KEY is still a placeholder.",
          expect.stringContaining("Argument contains shell-like syntax:"),
        ]),
      );
    });

    it("warns on unpinned docker image operands", () => {
      const report = validateServer("dock", {
        command: "docker",
        args: ["run", "ghcr.io/example/mcp:latest"],
      });
      expect(report.packageName).toBe("ghcr.io/example/mcp:latest");
      expect(report.warnings.join("\n")).not.toContain("runs unpinned package");
    });

    it("uses stdio transport when only command is present", () => {
      expect(
        validateServer("stdio-only", {
          command: "npx",
          args: ["-y", "@example/mcp"],
        }),
      ).toMatchObject({
        transport: "stdio",
        command: "npx",
      });

      expect(
        validateServer("remote-only", {
          url: "https://example.com/mcp",
        }),
      ).toMatchObject({
        transport: "remote",
        command: "",
      });

      expect(validateServer("unknown-only", {})).toMatchObject({
        transport: "unknown",
      });

      expect(
        validateServer("   ", {
          command: "npx",
          args: ["-y", "@example/mcp@1.2.3"],
        }),
      ).toMatchObject({
        name: "   ",
        transport: "stdio",
      });
    });

    it("falls back when sanitized server config is not a record", () => {
      const spy = vi
        .spyOn(serverSanitize, "getServerSanitization")
        .mockReturnValueOnce({
          sanitizedRawValue: {},
          sanitizedArgs: [],
          redactedSecretCount: 0,
        });
      const report = validateServer("shell", {
        command: "npx",
        args: [";danger"],
      });
      expect(report.warnings.join("\n")).toContain(
        "Argument contains shell-like syntax: ${SECRET}",
      );
      spy.mockRestore();
    });
  });

  describe("getServerSanitization", () => {
    it("falls back when sanitized root value is not a record", () => {
      const spy = vi
        .spyOn(mcpValidatorLib, "sanitizeConfigValue")
        .mockReturnValueOnce({ value: [], redactedCount: 2 });
      expect(
        getServerSanitization({ command: "npx", args: ["-y", "@example/mcp"] }),
      ).toEqual({
        sanitizedRawValue: {},
        sanitizedArgs: [],
        redactedSecretCount: 2,
      });
      spy.mockRestore();
    });
  });

  describe("buildReportText", () => {
    it("summarizes validation output for pass and blocked runs", () => {
      const pass = buildReportText({
        ok: true,
        errors: [],
        warnings: [],
        servers: [
          {
            name: "github",
            transport: "stdio",
            packageName: "@example/mcp",
            envKeys: ["TOKEN"],
            errors: [],
            warnings: [],
          },
        ],
        fixedConfigText: "{}",
        redactedSecretCount: 2,
      });
      expect(pass).toContain("MCP config validation: pass");
      expect(pass).toContain("Redacted secrets: 2");
      expect(pass).toContain("## github");
      expect(pass).toContain("Package: @example/mcp");

      const remote = buildReportText({
        ok: true,
        errors: [],
        warnings: [],
        servers: [
          {
            name: "remote",
            transport: "remote",
            url: "https://example.com/mcp",
            envKeys: [],
            errors: [],
            warnings: [],
          },
        ],
        fixedConfigText: "{}",
        redactedSecretCount: 0,
      });
      expect(remote).toContain("URL: https://example.com/mcp");
      expect(remote).toContain("Env keys: none");

      const blocked = buildReportText({
        ok: false,
        errors: ["demo: url must be a valid URL."],
        warnings: ["demo: TOKEN is still a placeholder."],
        servers: [
          {
            name: "demo",
            transport: "remote",
            envKeys: [],
            errors: ["url must be a valid URL."],
            warnings: ["TOKEN is still a placeholder."],
          },
        ],
        fixedConfigText: "",
        redactedSecretCount: 0,
      });
      expect(blocked).toContain("MCP config validation: blocked");
      expect(blocked).toContain("- Error: url must be a valid URL.");
      expect(blocked).toContain("- Warning: TOKEN is still a placeholder.");
    });
  });

  describe("asStringArray", () => {
    it("filters non-string array entries", () => {
      expect(asStringArray(["ok", 1, null, "also-ok"])).toEqual([
        "ok",
        "also-ok",
      ]);
      expect(asStringArray("nope")).toEqual([]);
    });
  });

  describe("isRecord", () => {
    it("narrows plain objects", () => {
      expect(isRecord({})).toBe(true);
      expect(isRecord([])).toBe(false);
      expect(isRecord(null)).toBe(false);
    });
  });
});
